const A_FETCH = 'A_FETCH'
const A_SUCCESS = 'A_SUCCESS'
const A_FAILURE = 'A_FAILURE'
const A_DELETE = 'A_DELETE'
const A_DELETE_FAILURE = 'A_DELETE_FAILURE'
const A_DELETE_SUCCESS = 'A_DELETE_SUCCESS'
const A_DELETE_PLAYLIST = 'A_DELETE_PLAYLIST'
const A_RESTART = 'A_RESTART'

const B_FETCH = 'B_FETCH'
const B_SUCCESS = 'B_SUCCESS'
const B_FAILURE = 'B_FAILURE'
const B_NEW_PLAYLIST = 'B_NEW_PLAYLIST'
const B_DELETE_PLAYLIST = 'B_DELETE_PLAYLIST'
const B_DELETE_VIDEO = 'B_DELETE_VIDEO'
const B_COMPARE_PLAYLIST = 'B_COMPARE_PLAYLIST'
const B_THROW = 'B_THROW'
const B_RESTART = 'B_RESTART'

const C_FETCH = 'C_FETCH'
const C_START = 'C_START'
const C_SUCCESS = 'C_SUCCESS'
const C_FAILURE = 'C_FAILURE'
const C_DELETE = 'C_DELETE'
const C_DELETE_FAILURE = 'C_DELETE_FAILURE'
const C_DELETE_SUCCESS = 'C_DELETE_SUCCESS'
const C_DELETE_PLAYLIST = 'C_DELETE_PLAYLIST'
const C_REBUILD_PLAYLIST = 'C_REBUILD_PLAYLIST'
const C_RESTART = 'C_RESTART'

const RESTART = 'RESTART'

module.exports = {
  A_FETCH,
  A_FAILURE,
  A_SUCCESS,
  B_FETCH,
  B_FAILURE,
  B_SUCCESS,
  C_FETCH,
  C_FAILURE,
  C_SUCCESS,
  C_DELETE,
  C_DELETE_SUCCESS,
  C_DELETE_FAILURE,
  B_NEW_PLAYLIST,
  B_DELETE_PLAYLIST,
  B_DELETE_VIDEO,
  B_COMPARE_PLAYLIST,
  A_DELETE,
  A_DELETE_FAILURE,
  A_DELETE_SUCCESS,
  A_DELETE_PLAYLIST,
  C_DELETE_PLAYLIST,
  C_START,
  B_THROW,
  A_RESTART,
  B_RESTART,
  C_RESTART,
  RESTART
}
